[package]

name = "hyper"
version = "0.10.0-a.0"
description = "A modern HTTP library."
readme = "README.md"
documentation = "http://hyperium.github.io/hyper"
repository = "https://github.com/hyperium/hyper"
license = "MIT"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
keywords = ["http", "hyper", "hyperium"]

[dependencies]
futures = "0.1"
futures-cpupool = "0.1"
httparse = "1.0"
language-tags = "0.2"
log = "0.3"
mime = "0.2"
mio = "0.6"
rustc-serialize = "0.3"
spmc = "0.2"
time = "0.1"
tokio-core = "0.1"
tokio-proto = {git = "https://github.com/tokio-rs/tokio-proto"}
tokio-service = {git = "https://github.com/tokio-rs/tokio-service"}
unicase = "1.0"
url = "1.0"
vecio = "0.1"

[dependencies.cookie]
version = "0.3"
default-features = false

[dependencies.serde]
version = "0.8"
optional = true

[dev-dependencies]
num_cpus = "1.0"
#env_logger = "0.3"
pretty_env_logger = { git = "https://github.com/seanmonstar/pretty-env-logger" }

[features]
default = []
serde-serialization = ["serde", "mime/serde"]
nightly = []
